### ISSUE TITLE
"mrsm show pipes" generates a database connection error. 

### ISSUE THREAD

**Issue by whitedl** [bmeares/Meerschaum#51]
Primary issue appears to indicate that MRSM and TimescaleDB are not able to communicate. I have verified that mrsm_db_1 is running in Docker. 

CONTAINER ID   IMAGE                                   COMMAND                  CREATED        STATUS                          PORTS     NAMES
c3a41726b5b9   timescale/timescaledb:latest-pg13-oss   "docker-entrypoint.s…"   12 hours ago   Restarting (1) 25 seconds ago             mrsm_db_1

**Previous communication**
"You can use the preconfigured docker-compose stack, just run mrsm stack up -d db to get TimescaleDB up. You can first set the password with mrsm edit config before running mrsm stack up -d db or you can change the password later (default is username:  mrsm and password: mrsm)."

Note: there is no mrsm user on the system only my azureuser

----------------------------------
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
-----------------------------------
Setup/Install Notes:
1. Setup DOCKER on Azure VM (needed to add "azureuser", sudo usermod -a -G docker azureuser)
2. pip install meerschaum (mrsm was installed in /home/.local/bin and needed to add to PATH)
3. mrsm stack up -d db
4. test mrsm install "$mrsm" successfully starts mrsm session (everything looks good)
5. mrsm show pipes generates the following error:

⚠️ (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
(Background on this error at: https://sqlalche.me/e/14/e3q8)
  warn(str(e))
 💢 Failed to execute 'show pipes' with exception:
' 🛑 (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
(Background on this error at: https://sqlalche.me/e/14/e3q8)'.
Run again with '--debug' to see a full stacktrace.

**Comment by bmeares** [comment]
Spoke with @whitedl and verified that the TimescaleDB container wasn't starting because the VM was out of RAM. For those reading in the future, the `mrsm` user is the default a Meerschaum user for TimescaleDB not a system user.
