### ISSUE TITLE
Credentials needed to delete a plugin

### ISSUE THREAD

**Issue by whitedl** [bmeares/Meerschaum#54]
Trying to delete a plugin, but receive an error requiring authentication "login api:mrsm".  Can not recall setting credentials for this connector and unable to locate reference for default credentials in docs.
![Screen Shot 2022-02-01 at 12 08 53 PM](https://user-images.githubusercontent.com/8012877/152016425-5001c3a5-22ea-47b9-80ba-45fe57fd5932.png)
.

**Comment by bmeares** [comment]
Hi @whitedl , thanks for posting! You can remove the plugin from your machine with `uninstall plugin twitter_2`. The `delete plugin` command removes a plugin from a repository if you've published it (via `register plugin`). [Here is some information](https://meerschaum.io/reference/plugins/list-of-plugins/) on adding your plugin to the [public plugin repo](https://api.mrsm.io/dash/plugins), and [this page](https://meerschaum.io/reference/plugins/using-plugins/) has information on hosting plugins on your own private repository.

You can also remove a plugin by deleting it from the `~/.config/meerschaum/plugins/` folder.

I hope this helps!
